---
name: Test-Rest
version: 0.02
author:
  - 'Keith Grennan <kgrennan@cpan.org>'
abstract: Declarative test framework for RESTful web services
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::MockObject: 1.09
  Test::More: 0.94
requires:
  Class::Accessor: 0.31
  LWP::UserAgent: 5.834
  String::Random: 0.22
  Template: 2.22
  URI: 1.40
  WWW::Mechanize: 1.60
  XML::LibXML: 1.70
configure_requires:
  Module::Build: 0.35
provides:
  Test::Rest:
    file: lib/Test/Rest.pm
    version: 0.02
  Test::Rest::Commands:
    file: lib/Test/Rest/Commands.pm
  Test::Rest::Context:
    file: lib/Test/Rest/Context.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
